service: echo-bot
provider:
  name: aws
  runtime: nodejs8.10
  stage: production
  region: ap-northeast-2

plugins:
  - serverless-webpack
  - serverless-dotenv-plugin

functions:
  webhook:
    handler: src/index.webhook
    memorySize: 128
    timeout: 5
    environment:
      CHANNEL_SECRET: ${env:CHANNEL_SECRET}
      CHANNEL_ACCESS_TOKEN: ${env:CHANNEL_ACCESS_TOKEN}
    events:
      - http:
          path: webhook
          method: post
